//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HistoricalDBEntities : DbContext
    {
        public HistoricalDBEntities()
            : base("name=HistoricalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sensor> Sensor { get; set; }
        public DbSet<SensorGroup> SensorGroup { get; set; }
        public DbSet<SensorHistoryData> SensorHistoryData { get; set; }
    }
}
