//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorHistoryData
    {
        public int SensorHistoryDataId { get; set; }
        public Nullable<int> SensorId { get; set; }
        public string DataText { get; set; }
        public Nullable<decimal> DataNumeric { get; set; }
        public Nullable<System.DateTime> SampledDT { get; set; }
        public Nullable<System.DateTime> InsertedDT { get; set; }
    
        public virtual Sensor Sensor { get; set; }
    }
}
