//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.SensorHistoryData = new HashSet<SensorHistoryData>();
        }
    
        public int SensorId { get; set; }
        public Nullable<int> SensorGroupId { get; set; }
        public string Name { get; set; }
        public string Dimension { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual SensorGroup SensorGroup { get; set; }
        public virtual ICollection<SensorHistoryData> SensorHistoryData { get; set; }
    }
}
