#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Website.Data;

namespace Website.Data	
{
	public partial class HMonitorData : OpenAccessContext, IHMonitorDataUnitOfWork
	{
		private static string connectionStringName = @"HMonitorDataConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public HMonitorData()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public HMonitorData(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public HMonitorData(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public HMonitorData(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public HMonitorData(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<SensorHistoryData> SensorHistoryDatas 
		{
			get
			{
				return this.GetAll<SensorHistoryData>();
			}
		}
		
		public IQueryable<SensorGroup> SensorGroups 
		{
			get
			{
				return this.GetAll<SensorGroup>();
			}
		}
		
		public IQueryable<Sensor> Sensors 
		{
			get
			{
				return this.GetAll<Sensor>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}
	
	public interface IHMonitorDataUnitOfWork : IUnitOfWork
	{
		IQueryable<SensorHistoryData> SensorHistoryDatas
		{
			get;
		}
		IQueryable<SensorGroup> SensorGroups
		{
			get;
		}
		IQueryable<Sensor> Sensors
		{
			get;
		}
	}
}
#pragma warning restore 1591
