#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Website.Data;

namespace Website.Data	
{
	public partial class SensorHistoryData
	{
		private int _sensorHistoryDataId;
		public virtual int SensorHistoryDataId
		{
			get
			{
				return this._sensorHistoryDataId;
			}
			set
			{
				this._sensorHistoryDataId = value;
			}
		}
		
		private int? _sensorId;
		public virtual int? SensorId
		{
			get
			{
				return this._sensorId;
			}
			set
			{
				this._sensorId = value;
			}
		}
		
		private string _dataText;
		public virtual string DataText
		{
			get
			{
				return this._dataText;
			}
			set
			{
				this._dataText = value;
			}
		}
		
		private decimal? _dataNumeric;
		public virtual decimal? DataNumeric
		{
			get
			{
				return this._dataNumeric;
			}
			set
			{
				this._dataNumeric = value;
			}
		}
		
		private DateTime? _sampledDT;
		public virtual DateTime? SampledDT
		{
			get
			{
				return this._sampledDT;
			}
			set
			{
				this._sampledDT = value;
			}
		}
		
		private DateTime? _insertedDT;
		public virtual DateTime? InsertedDT
		{
			get
			{
				return this._insertedDT;
			}
			set
			{
				this._insertedDT = value;
			}
		}
		
		private Sensor _sensor;
		public virtual Sensor Sensor
		{
			get
			{
				return this._sensor;
			}
			set
			{
				this._sensor = value;
			}
		}
		
	}
}
#pragma warning restore 1591
