#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Website.Data;

namespace Website.Data	
{
	public partial class Sensor
	{
		private int _sensorId;
		public virtual int SensorId
		{
			get
			{
				return this._sensorId;
			}
			set
			{
				this._sensorId = value;
			}
		}
		
		private int? _sensorGroupId;
		public virtual int? SensorGroupId
		{
			get
			{
				return this._sensorGroupId;
			}
			set
			{
				this._sensorGroupId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _dimension;
		public virtual string Dimension
		{
			get
			{
				return this._dimension;
			}
			set
			{
				this._dimension = value;
			}
		}
		
		private string _comment;
		public virtual string Comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment = value;
			}
		}
		
		private bool? _active;
		public virtual bool? Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private string _code;
		public virtual string Code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		
		private SensorGroup _sensorGroup;
		public virtual SensorGroup SensorGroup
		{
			get
			{
				return this._sensorGroup;
			}
			set
			{
				this._sensorGroup = value;
			}
		}
		
		private IList<SensorHistoryData> _sensorHistoryData = new List<SensorHistoryData>();
		public virtual IList<SensorHistoryData> SensorHistoryData
		{
			get
			{
				return this._sensorHistoryData;
			}
		}
		
	}
}
#pragma warning restore 1591
